apiVersion: v1
kind: Service
metadata:
  name: fproject-backend-service
  namespace: default
  labels:
    app: fproject-backend
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 3001
    nodePort: 31663
    protocol: TCP
    name: http
  selector:
    app: fproject-backend
